require 'spec_helper'
require 'mail'

#TODO: Move to spec_helper?
def basic_sortah_definition
  sortah do
    maildir "/home/jfredett/.mail"
    destination :foo, "foo/"
    destination :bar, "bar/"
    router do
      if email.from.any? { |sender| sender =~ /chuck/ } 
        send_to :foo
      else
        send_to :bar
      end
    end
  end
end

describe Sortah do
  context "when sorting an email" do
    before :all do
      Mail.defaults do
        delivery_method :test
      end

      @email = Mail.new do
        to 'testa@example.com'
        from 'chuck@nope.com'
        subject "Taximerdizin'"
        body <<-TXT
          OJAI VALLEY TAXIDERMY

          BET YOU THOUGHT THIS EMAIL WAS REAL

          NOPE. CHUCK TESTA
        TXT
      end

      @reply_email = Mail.new do
        to 'chuck@nope.com'
        from 'jgf@somewhere.com'
        subject "Re: Taximerdizin'"
        reply_to 'chuck@nope.com'
        body <<-TXT
        > OJAI VALLEY TAXIDERMY
        >
        > BET YOU THOUGHT THIS EMAIL WAS REAL
        >
        > NOPE. CHUCK TESTA

        Do you taxidermize pets? 
        TXT
      end
    end

    before :each do
      Sortah::Parser.clear
    end

    it "should provide a way to sort a single email" do
      sortah.should respond_to :sort
    end

    it "should throw a sematic error when calling #sort with no root router is provided" do
      sortah do 
        destination :foo, "foo/"
        router :not_root do
          send_to :foo
        end
      end
      expect { sortah.sort(@email) }.should raise_error Sortah::NoRootRouterException
    end

    describe "#sort" do
      it "should return an object which responds to #destination" do
        basic_sortah_definition
        sortah.sort(@email).should respond_to :destination
      end

      it "should return an object which responds to #metadata" do
        basic_sortah_definition
        sortah.sort(@email).should respond_to :metadata
      end
      
      it "should sort emails based on the sortah definitions" do
        basic_sortah_definition
        sortah.sort(@email).destination.should == "foo/"
        sortah.sort(@reply_email).destination.should == "bar/"
      end

      it "should defer to a second router if it is sent to one" do
        sortah do
          destination :foo, "foo/"
          destination :bar, "bar/"
          
          router do
            if email.from.any? { |sender| sender =~ /chuck/ }
              send_to :foo
            else
              send_to :secondary_router
            end
          end

          router :secondary_router do
            send_to :bar
          end
        end
        
        sortah.sort(@email).destination.should == "foo/"
        sortah.sort(@reply_email).destination.should == "bar/"
      end

      it "should run dependent lenses for the root router" do
        sortah do
          destination :foo, "foo/"
         
          lens :senders do
            email.from.map { |s| s.split('@').first }
          end

          router :root, :lenses => [:senders] do
            send_to :foo
          end
        end
        sortah.sort(@email).metadata[:senders].should == ["chuck"]
      end

      it "should run dependent lenses for the non-root router, but only if the router gets called" do
        sortah do
          destination :foo, "foo/"
         
          lens :senders do
            email.from.map { |s| s.split('@').first }
          end

          lens :never_called do
            "This should never be called, since the router that depends on it never gets called"
          end

          router :root, :lenses => [:senders] do
            send_to :foo
          end

          router :bar, :lenses => [:never_called] do
            "doesn't matter what I put in here"
          end
        end
        sortah.sort(@email).metadata[:never_called].should be_nil
      end

      it "should never run a lens that isn't a dependency" do
        sortah do
          destination :foo, "foo/"
         
          lens :senders do
            email.from.map { |s| s.split('@').first }
          end

          lens :never_called do
            "This should never be called, since the router that depends on it never gets called"
          end

          router :root, :lenses => [:senders] do
            send_to :foo
          end
        end
        sortah.sort(@email).metadata[:never_called].should be_nil
      end

      it "should run provide access to the metadata generated by a lens through the email object" do
        sortah do
          destination :foo, "foo/"
          destination :bar, "bar/"
         
          lens :senders do
            email.from.map { |s| s.split('@').first }
          end

          lens :never_called do
            "This should never be called, since the router that depends on it never gets called"
          end

          router :root, :lenses => [:senders] do
            if email.senders.include? "chuck"
              send_to :foo
            else
              send_to :bar
            end
          end
        end
        sortah.sort(@email).destination.should == "foo/"
        sortah.sort(@reply_email).destination.should == "bar/"
      end

    end
  end
end
